<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Loops (Good) Exercises</span></div>

## Exercise 1

In [5]:
for number in range(10):
    if number % 2 == 0:
        continue 
    square = number**2
    print(square)

1
9
25
49
81


## Exercise 2

In [9]:
[number**2 for number in range(10) if number % 2 != 0]

[1, 9, 25, 49, 81]

## Exercise 3

In [13]:
%%timeit
for number in range(10):
    if number % 2 == 0:
        continue 
    square = number**2

394 ns ± 1.81 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
%%timeit
[number**2 for number in range(10) if number % 2 != 0]

487 ns ± 1.74 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


The first method is faster!

## Exercise 4

In [6]:
for year in range(1,100):
    number = 100*0.95**year
    if number < 50:
        break
    print(f'Year{year}{":"} {number}')

Year1: 95.0
Year2: 90.25
Year3: 85.73749999999998
Year4: 81.45062499999999
Year5: 77.37809374999998
Year6: 73.50918906249998
Year7: 69.83372960937497
Year8: 66.34204312890623
Year9: 63.02494097246091
Year10: 59.87369392383787
Year11: 56.880009227645964
Year12: 54.03600876626366
Year13: 51.33420832795048


## Exercise 5

In [1]:
co2_data = [
    (2000, 369.55), (2001, 371.14), (2002, 373.28), 
    (2003, 375.80), (2004, 377.52), (2005, 379.80), 
    (2006, 381.90), (2007, 383.79), (2008, 385.60), 
    (2009, 387.43), (2010, 389.90), (2011, 391.65), 
    (2012, 393.85), (2013, 396.52), (2014, 398.65),
    (2015, 400.83), (2016, 404.24), (2017, 406.55), 
    (2018, 408.52), (2019, 411.44), (2020, 414.24)
]
import numpy as np
np_co2_data = np.array(co2_data)
np_co2_data[:-1,1]

array([369.55, 371.14, 373.28, 375.8 , 377.52, 379.8 , 381.9 , 383.79,
       385.6 , 387.43, 389.9 , 391.65, 393.85, 396.52, 398.65, 400.83,
       404.24, 406.55, 408.52, 411.44])

In [2]:
np_co2_data[1:,1]

array([371.14, 373.28, 375.8 , 377.52, 379.8 , 381.9 , 383.79, 385.6 ,
       387.43, 389.9 , 391.65, 393.85, 396.52, 398.65, 400.83, 404.24,
       406.55, 408.52, 411.44, 414.24])

In [11]:
np_co2_data[1:,1] - np_co2_data[:-1,1]

array([1.59, 2.14, 2.52, 1.72, 2.28, 2.1 , 1.89, 1.81, 1.83, 2.47, 1.75,
       2.2 , 2.67, 2.13, 2.18, 3.41, 2.31, 1.97, 2.92, 2.8 ])

In [12]:
np_co2_change = np_co2_data[1:,1] - np_co2_data[:-1,1]

In [4]:
np_co2_data_2 = np_co2_data[1:]
np_co2_data_2[np_co2_data[1:,1] - np_co2_data[:-1,1] >3]

array([[2016.  ,  404.24]])

In [21]:
print(np_co2_data[16,0].astype(int), np_co2_change[-5])

2016 3.410000000000025
