<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

- **Subsetting** means to ‘select’.
- **Indexing** refers to selecting one element.
- **Slicing** refers to selecting a range of elements.

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
x = py_list

In [4]:
x[1:6] #gives index 1 to 5

['b2', 'c3', 'd4', 'e5', 'f6']

In [5]:
x[1:10:2] #gives every other of element 1 to 9, starting from element 1

['b2', 'd4', 'f6', 'h8', 'j10']

In [6]:
x[5:] #gives element 5 to the last element

['f6', 'g7', 'h8', 'i9', 'j10']

In [7]:
x[:5] #gives first element to element 4

['a1', 'b2', 'c3', 'd4', 'e5']

In [8]:
x[5:2:-1] #gives index 5 to 3 in reverse

['f6', 'e5', 'd4']

In [9]:
x[::-1] #reverses the entire list

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

In [12]:
import numpy as np

In [13]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3

In [14]:
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [15]:
np_array[my_mask] #ask NumPy to show only those that are TRUE

array([ 4,  5,  6,  7,  8,  9, 10])

In [16]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
np_array[~(np_array > 3)] #invert the mask i.e. ~ = NOT

array([1, 2, 3])

In [18]:
np_array[(np_array > 3) & (np_array < 8)] #& = AND

array([4, 5, 6, 7])

In [19]:
np_array[(np_array < 3) | (np_array > 8)] #| = OR

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [20]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [21]:
py_list_2d[3]

[4, 'D']

In [22]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [23]:
py_list_2d[3][0] #FIRST element for index 3

4

In [24]:
np_array_2d[3, 0]

'4'

In [25]:
py_list_2d[:3] #first 3 indexes

[[1, 'A'], [2, 'B'], [3, 'C']]

In [26]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [27]:
py_list_2d[:3][0] #gives first index of the list from py_list_2d[:3], NOT first element of first 3 indexes

[1, 'A']

In [29]:
py_list_2d[3:6][0] #gives first index of the list also

[4, 'D']

In [28]:
np_array_2d[:3, 0] #gives first element of first 3 indexes

array(['1', '2', '3'], dtype='<U21')

In [30]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U21')

In [31]:
np_array_2d[:, 0] #every first element of ALL indexes

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [32]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [33]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [34]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [36]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x #runs faster than the above!

[1, 2, 3, 4]

In [37]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [38]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [39]:
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [41]:
a=(1, 2, 3) #define tuple
print(a[0]) #access data, BUT cannot change data e.g. make list 

1


## 1.6 Be VERY careful when copying

In [42]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes