<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"] #order of each individual to name matters
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [ ]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [ ]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange" 
}  #very useful, holds everything in 1 structure

## 1.2 Accessing data from a list (or array)

In [2]:
py_real_names[0]

'Natasha Romanoff'

In [3]:
py_super_names[0]

'Black Widow'

In [5]:
py_super_names[2] #forward indexing, need to know the size beforehand to work

'Doctor Strange'

In [6]:
py_super_names[-1] #reverse indexing, always gives the last element

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [8]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange" 
}  #very useful, holds everything in 1 structure

In [9]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [10]:
superhero_info.keys() #access all keys

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [11]:
superhero_info.values() #access all values

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [12]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']] #2D list

In [15]:
py_superhero_info[2]

['Stephen Strange', 'Doctor Strange']

# 2 Lists vs. Arrays

## 2.1 Size

In [20]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [21]:
len(py_list_2d)

10

In [32]:
import numpy as np # remember to import numpy package before using!!!

In [33]:
np_array_2d = np.array(py_list_2d)      # Reusing the Python list to create a NEW NumPy array

In [34]:
len(np_array_2d)

10

In [35]:
np_array_2d.shape #shape is not a function, so no need brackets

(10, 2)

## 2.2 Arrays are fussy about type

In [36]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [37]:
py_list

[1, 1.5, 'A']

In [38]:
np_array #Remember that NumPy arrays tolerate only a single type – numbers are converted to English (' ')

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [39]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [40]:
np_array + 10 #py_list +10 will NOT work

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [42]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [44]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [43]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)    

In [45]:
py_list*2 #makes list double, retaining same elements

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [46]:
np_array*2 #array multiplies elements by the number

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [47]:
np_array**2 #won't work for py_list

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 

In [48]:
py_list == 3

False

In [56]:
py_list == 3 #don't ask such questions to list

False

In [49]:
np_array == 3 #are individual elements equal to the number?

array([False, False,  True, False, False])

In [50]:
np_array > 3 #are individual elements greater than the number?

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [57]:
sum(py_list)     # sum() is a base Python function

15

In [58]:
max(py_list)     # max() is a base Python function

5

In [59]:
min(py_list)     # min() is a base Python function

1

In [60]:
np_array.sum()

15

In [61]:
np_array.max()

5

In [62]:
np_array.min()

1

In [63]:
np_array.mean()

3.0

In [64]:
np_array.std()

1.4142135623730951

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes